FROM python:alpine

ARG VERSION

RUN apk update --no-cache
RUN apk add --no-cache whois
RUN pip install --no-cache-dir -i https://test.pypi.org/simple/ whoisdomain==$VERSION

ENTRYPOINT ["whoisdomain"]
CMD ["--help"]
