# Makefile

SHELL := /bin/bash -l
export SHELL

VENV := ./vtmp/
export VENV

# tested on 3.10-3.14
MIN_PYTHON_VERSION := $(shell basename $$( ls /usr/bin/python3.[0-9][0-9] | awk '{print $0; exit}' ) )
export MIN_PYTHON_VERSION

# ==========================================
# Code formatting and checks
PY_FILES := *.py bin/*.py whoisdomain/

LINE_LENGTH := 160

TEST_OPTIONS_ALL = \
	--withPublicSuffix \
	--extractServers \
	--stripHttpStatus

.PHONY: test1 test2 test3 test4 testwith

# --------------------------------------------------
# Tests
# --------------------------------------------------
test: test1 testwith test2 test3 test4

test1:
	./test1.py | tee tmp/$@.1

# test2 has the data type in the output
test2:
	./test2.py -f testdata/DOMAINS.txt 2>tmp/$@.2 | tee tmp/$@.1

# test3 simulates the whoisdomain command and has no data type in the output
test3:
	./test3.py -f testdata/DOMAINS.txt 2>tmp/$@.2 | tee tmp/$@.1

test4:
	LOGLEVEL=DEBUG ./test2.py $(TEST_OPTIONS_ALL) -t 2>tmp/$@.2 | tee tmp/$@.1

testwith: withPublicSuffix withExtractServers stripHttpStatus

withPublicSuffix:
	./test2.py -d  www.dublin.airport.aero --withPublicSuffix

withExtractServers:
	./test2.py -d google.com --extractServers

stripHttpStatus:
	./test2.py -d nic.aarp --stripHttpStatus
	./test2.py -d nic.abudhabi --stripHttpStatus
	./test2.py -d META.AU --stripHttpStatus
	./test2.py -d google.AU --stripHttpStatus
