
google:
	/usr/bin/python3 ./test-google-tld.py 2>2 | tee 1

redacted:
	# show redacted output anyway
	/usr/bin/python3 ./testWithRedacted.py

fr:
	/usr/bin/python3 ./testFr.py

cache:
	/usr/bin/python3 ./testCache.py
