name: "lint"
on: [push, pull_request]
jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy tld
          python3 -m pip install types-redis
          python3 -m pip install types-requests

      - name: Run mypy
        run: mypy --strict *.py whoisdomain
