name: Demonstration SCAN

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build_wheel:
    env:
      BUILD_VERSION: $(cat work/version)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ==================================================================      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
          
      # ==================================================================      
      - name: Build wheel
        run: |
          python -m pip install --user --upgrade build
          python -m build
          ls dist/whoisdomain*${BUILD_VERSION}*.whl | xargs pip install
          
      # ==================================================================      
      - name: prepare for rl-scanner
        run: |
          rm -rf report # we need a empty report directory
          mkdir -p packages report-${BUILD_VERSION} # prepare the 2 volume mounts
          cp dist/whoisdomain*${BUILD_VERSION}*.whl packages # copy the package to scan to the input volume location

      # ==================================================================      
      - name: Test with rl-scanner
        env: # use environment variables
          RL_DEPLOY_SITE_KEY: ${{ secrets.RL_DEPLOY_SITE_KEY }}
          RL_DEPLOY_ENCODED_KEY: ${{ secrets.RL_DEPLOY_ENCODED_KEY }}
        run: |
          docker run --pull always --rm \
            -u $(id -u):$(id -g) \
            -v "$(pwd)/packages:/packages:ro" \
            -v "$(pwd)/report-${BUILD_VERSION}:/report" \
            -e RLSECURE_ENCODED_LICENSE="${RL_DEPLOY_ENCODED_KEY}" \
            -e RLSECURE_SITE_KEY="${RL_DEPLOY_SITE_KEY}" \
            reversinglabs/rl-scanner \
            rl-scan \
                --package-path=/packages/whoisdomain*${BUILD_VERSION}*.whl \
                --report-path=/report \
                --report-format=all

      # ==================================================================      
      - name: Archive Report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: report-${BUILD_VERSION}
          path: report
